version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: entre_paginas_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: entre_paginas
    ports:
      - "5433:5432" # Utiliza a porta 5433 no host se o PostgreSQL local já estiver na 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
