import { ProviderCapabilities } from './types';

export interface ProviderDefinition {
  id: string;
  displayName: string;
  baseUrl: string;
  enabled: boolean;
  priority: number;
  timeoutMs: number;
  requiresApiKey: boolean;
  apiKeyEnvVar?: string;
  credentialsEnvVars?: string[];
  rateLimit: {
    maxRequestsPerMinute: number;
    maxConcurrent: number;
    retry: number;
  };
  capabilities: ProviderCapabilities;
  licenseDefault: string;
  description: string;
}

export const PROVIDERS_REGISTRY_CONFIG: Record<string, ProviderDefinition> = {
  openlibrary: {
    id: 'openlibrary',
    displayName: 'Open Library',
    baseUrl: 'https://openlibrary.org',
    enabled: true,
    priority: 10,
    timeoutMs: 8000,
    requiresApiKey: false,
    rateLimit: {
      maxRequestsPerMinute: 90,
      maxConcurrent: 3,
      retry: 2,
    },
    capabilities: {
      search: true,
      metadata: true,
      covers: true,
      fullText: false,
      preview: false,
      legalDownload: false,
      libraryBorrow: false,
      audiobook: false,
      physicalCopy: false,
      isbnLookup: true,
      multilingual: true,
      availability: true,
    },
    licenseDefault: 'Consulta Bibliográfica & Metadados Abertos',
    description: 'Catálogo aberto global com registros de obras, edições, ISBNs e capas em alta resolução.',
  },
  gutenberg: {
    id: 'gutenberg',
    displayName: 'Project Gutenberg',
    baseUrl: 'https://gutendex.com/books',
    enabled: true,
    priority: 9,
    timeoutMs: 8000,
    requiresApiKey: false,
    rateLimit: {
      maxRequestsPerMinute: 60,
      maxConcurrent: 2,
      retry: 2,
    },
    capabilities: {
      search: true,
      metadata: true,
      covers: true,
      fullText: true,
      preview: false,
      legalDownload: true,
      libraryBorrow: false,
      audiobook: false,
      physicalCopy: false,
      isbnLookup: false,
      multilingual: true,
      availability: true,
    },
    licenseDefault: 'Domínio Público (Public Domain)',
    description: 'Mais de 70.000 obras completas em domínio público nos formatos EPUB, MOBI e HTML.',
  },
  standard_ebooks: {
    id: 'standard_ebooks',
    displayName: 'Standard Ebooks',
    baseUrl: 'https://standardebooks.org/opds',
    enabled: true,
    priority: 8,
    timeoutMs: 8000,
    requiresApiKey: false,
    rateLimit: {
      maxRequestsPerMinute: 30,
      maxConcurrent: 2,
      retry: 2,
    },
    capabilities: {
      search: true,
      metadata: true,
      covers: true,
      fullText: true,
      preview: false,
      legalDownload: true,
      libraryBorrow: false,
      audiobook: false,
      physicalCopy: false,
      isbnLookup: false,
      multilingual: false,
      availability: true,
    },
    licenseDefault: 'Domínio Público / CC0 1.0',
    description: 'Ebooks em domínio público cuidadosamente editados e tipograficamente refinados.',
  },
  librivox: {
    id: 'librivox',
    displayName: 'LibriVox Audiobooks',
    baseUrl: 'https://librivox.org/api/feed/audiobooks',
    enabled: true,
    priority: 8,
    timeoutMs: 9000,
    requiresApiKey: false,
    rateLimit: {
      maxRequestsPerMinute: 45,
      maxConcurrent: 2,
      retry: 2,
    },
    capabilities: {
      search: true,
      metadata: true,
      covers: false,
      fullText: false,
      preview: false,
      legalDownload: true,
      libraryBorrow: false,
      audiobook: true,
      physicalCopy: false,
      isbnLookup: false,
      multilingual: true,
      availability: true,
    },
    licenseDefault: 'Domínio Público (Gravações voluntárias)',
    description: 'Audiolivros integrais em domínio público gravados por voluntários ao redor do mundo.',
  },
  internet_archive: {
    id: 'internet_archive',
    displayName: 'Internet Archive',
    baseUrl: 'https://archive.org',
    enabled: true,
    priority: 7,
    timeoutMs: 9000,
    requiresApiKey: false,
    rateLimit: {
      maxRequestsPerMinute: 60,
      maxConcurrent: 2,
      retry: 2,
    },
    capabilities: {
      search: true,
      metadata: true,
      covers: true,
      fullText: true,
      preview: true,
      legalDownload: true,
      libraryBorrow: true,
      audiobook: false,
      physicalCopy: false,
      isbnLookup: true,
      multilingual: true,
      availability: true,
    },
    licenseDefault: 'Acesso Aberto & Empréstimo Digital Controlado',
    description: 'Biblioteca digital sem fins lucrativos com digitalizações históricas em PDF e EPUB.',
  },
  google_books: {
    id: 'google_books',
    displayName: 'Google Books',
    baseUrl: 'https://www.googleapis.com/books/v1/volumes',
    enabled: true,
    priority: 9,
    timeoutMs: 7000,
    requiresApiKey: false,
    apiKeyEnvVar: 'GOOGLE_BOOKS_API_KEY',
    rateLimit: {
      maxRequestsPerMinute: 60,
      maxConcurrent: 3,
      retry: 2,
    },
    capabilities: {
      search: true,
      metadata: true,
      covers: true,
      fullText: false,
      preview: true,
      legalDownload: false,
      libraryBorrow: false,
      audiobook: false,
      physicalCopy: false,
      isbnLookup: true,
      multilingual: true,
      availability: true,
    },
    licenseDefault: 'Metadados & Pré-visualização Comercial',
    description: 'Catálogo abrangente de livros, sinopses, capas e identificadores ISBN comerciais.',
  },
  overdrive: {
    id: 'overdrive',
    displayName: 'OverDrive / Libby',
    baseUrl: 'https://api.overdrive.com/v1',
    enabled: true,
    priority: 6,
    timeoutMs: 8000,
    requiresApiKey: true,
    credentialsEnvVars: ['OVERDRIVE_CLIENT_KEY', 'OVERDRIVE_CLIENT_SECRET'],
    rateLimit: {
      maxRequestsPerMinute: 30,
      maxConcurrent: 1,
      retry: 1,
    },
    capabilities: {
      search: true,
      metadata: true,
      covers: true,
      fullText: false,
      preview: true,
      legalDownload: false,
      libraryBorrow: true,
      audiobook: true,
      physicalCopy: false,
      isbnLookup: true,
      multilingual: true,
      availability: true,
    },
    licenseDefault: 'Empréstimo Digital em Bibliotecas Parceiras (Libby)',
    description: 'Rede global de bibliotecas públicas com disponibilidade de empréstimo digital e reservas.',
  },
  worldcat: {
    id: 'worldcat',
    displayName: 'WorldCat (OCLC)',
    baseUrl: 'https://platform.worldcat.org/api-search',
    enabled: true,
    priority: 6,
    timeoutMs: 8000,
    requiresApiKey: true,
    apiKeyEnvVar: 'WORLDCAT_API_KEY',
    rateLimit: {
      maxRequestsPerMinute: 30,
      maxConcurrent: 1,
      retry: 1,
    },
    capabilities: {
      search: true,
      metadata: true,
      covers: false,
      fullText: false,
      preview: false,
      legalDownload: false,
      libraryBorrow: true,
      audiobook: false,
      physicalCopy: true,
      isbnLookup: true,
      multilingual: true,
      availability: true,
    },
    licenseDefault: 'Registro Bibliográfico Global de Bibliotecas',
    description: 'Maior rede global de dados bibliográficos e localização física/digital em bibliotecas.',
  },
  hathitrust: {
    id: 'hathitrust',
    displayName: 'HathiTrust Digital Library',
    baseUrl: 'https://catalog.hathitrust.org/api/volumes/brief',
    enabled: true,
    priority: 5,
    timeoutMs: 8000,
    requiresApiKey: false,
    rateLimit: {
      maxRequestsPerMinute: 40,
      maxConcurrent: 2,
      retry: 1,
    },
    capabilities: {
      search: true,
      metadata: true,
      covers: false,
      fullText: true,
      preview: true,
      legalDownload: false,
      libraryBorrow: false,
      audiobook: false,
      physicalCopy: false,
      isbnLookup: true,
      multilingual: true,
      availability: true,
    },
    licenseDefault: 'Patrimônio Acadêmico Digitalizado (Full View / Limited View)',
    description: 'Consórcio de instituições acadêmicas com milhões de volumes digitalizados.',
  },
  europeana: {
    id: 'europeana',
    displayName: 'Europeana Collections',
    baseUrl: 'https://api.europeana.eu/record/v2',
    enabled: true,
    priority: 5,
    timeoutMs: 8000,
    requiresApiKey: true,
    apiKeyEnvVar: 'EUROPEANA_API_KEY',
    rateLimit: {
      maxRequestsPerMinute: 45,
      maxConcurrent: 2,
      retry: 1,
    },
    capabilities: {
      search: true,
      metadata: true,
      covers: true,
      fullText: false,
      preview: true,
      legalDownload: false,
      libraryBorrow: false,
      audiobook: false,
      physicalCopy: false,
      isbnLookup: false,
      multilingual: true,
      availability: true,
    },
    licenseDefault: 'Acesso Aberto Europeu / Domínio Público',
    description: 'Patrimônio cultural, manuscritos e edições históricas de arquivos e museus europeus.',
  },
  wikisource: {
    id: 'wikisource',
    displayName: 'Wikisource',
    baseUrl: 'https://pt.wikisource.org/w/api.php',
    enabled: true,
    priority: 7,
    timeoutMs: 7000,
    requiresApiKey: false,
    rateLimit: {
      maxRequestsPerMinute: 90,
      maxConcurrent: 3,
      retry: 2,
    },
    capabilities: {
      search: true,
      metadata: true,
      covers: false,
      fullText: true,
      preview: false,
      legalDownload: false,
      libraryBorrow: false,
      audiobook: false,
      physicalCopy: false,
      isbnLookup: false,
      multilingual: true,
      availability: true,
    },
    licenseDefault: 'Creative Commons CC-BY-SA / Domínio Público',
    description: 'Biblioteca digital livre de textos-fonte integrais da Fundação Wikimedia em vários idiomas.',
  },
  doab: {
    id: 'doab',
    displayName: 'DOAB (Open Access Books)',
    baseUrl: 'https://directory.doabooks.org/rest',
    enabled: true,
    priority: 6,
    timeoutMs: 8000,
    requiresApiKey: false,
    rateLimit: {
      maxRequestsPerMinute: 45,
      maxConcurrent: 2,
      retry: 2,
    },
    capabilities: {
      search: true,
      metadata: true,
      covers: true,
      fullText: true,
      preview: false,
      legalDownload: true,
      libraryBorrow: false,
      audiobook: false,
      physicalCopy: false,
      isbnLookup: true,
      multilingual: true,
      availability: true,
    },
    licenseDefault: 'Open Access Acadêmico (Peer Reviewed)',
    description: 'Diretório global de livros acadêmicos revisados por pares em acesso aberto.',
  },
  oapen: {
    id: 'oapen',
    displayName: 'OAPEN Library',
    baseUrl: 'https://library.oapen.org/rest',
    enabled: true,
    priority: 6,
    timeoutMs: 8000,
    requiresApiKey: false,
    rateLimit: {
      maxRequestsPerMinute: 45,
      maxConcurrent: 2,
      retry: 2,
    },
    capabilities: {
      search: true,
      metadata: true,
      covers: true,
      fullText: true,
      preview: false,
      legalDownload: true,
      libraryBorrow: false,
      audiobook: false,
      physicalCopy: false,
      isbnLookup: true,
      multilingual: true,
      availability: true,
    },
    licenseDefault: 'Open Access Acadêmico Europeu',
    description: 'Biblioteca de publicações acadêmicas abertas nas áreas de humanas e ciências sociais.',
  },
  scielo_books: {
    id: 'scielo_books',
    displayName: 'SciELO Livros (Brasil)',
    baseUrl: 'http://books.scielo.org/api/v1',
    enabled: true,
    priority: 6,
    timeoutMs: 8000,
    requiresApiKey: false,
    rateLimit: {
      maxRequestsPerMinute: 40,
      maxConcurrent: 2,
      retry: 2,
    },
    capabilities: {
      search: true,
      metadata: true,
      covers: true,
      fullText: true,
      preview: true,
      legalDownload: true,
      libraryBorrow: false,
      audiobook: false,
      physicalCopy: false,
      isbnLookup: true,
      multilingual: true,
      availability: true,
    },
    licenseDefault: 'Creative Commons / Acesso Aberto Nacional',
    description: 'Coleção acadêmica de livros de editoras universitárias brasileiras e latino-americanas.',
  },
  lelivros: {
    id: 'lelivros',
    displayName: 'Le Livros (Descoberta)',
    baseUrl: process.env.LELIVROS_BASE_URL || 'https://lelivros.info',
    enabled: true,
    priority: 4,  // Prioridade baixa — fonte não verificada
    timeoutMs: 15000,  // Mais tempo para o pipeline de descoberta
    requiresApiKey: false,
    credentialsEnvVars: ['LELIVROS_BASE_URL'],
    rateLimit: {
      maxRequestsPerMinute: 10,  // Baixo para não sobrecarregar
      maxConcurrent: 1,
      retry: 1,
    },
    capabilities: {
      search: true,
      metadata: true,
      covers: true,
      fullText: false,
      preview: false,
      legalDownload: false,   // ⚠️ NUNCA true — fonte não verificada
      libraryBorrow: false,
      audiobook: false,
      physicalCopy: false,
      isbnLookup: false,
      multilingual: true,
      availability: true,
    },
    licenseDefault: '⚠️ Fonte Não Verificada — Autorização de Direitos Não Confirmada',
    description: 'Agente de descoberta de fonte pública. Demonstração técnica de multi-estratégia HTML scraping. Todo conteúdo classificado como UNVERIFIED_DOWNLOAD.',
  },
};
